version: '3.8'

services:
  torrent_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - QBITTORRENT_BASE_URL=${QBITTORRENT_BASE_URL}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - TMDB_KEY=${TMDB_KEY}
      - SUB_SEARCH_DIR=${SUB_SEARCH_DIR}
    volumes:
      - .:/app
      - /data/downloads:/downloads
