version: '3.8'

services:
  torrent_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - QBITTORRENT_BASE_URL=${QBITTORRENT_BASE_URL}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - JELLYFIN_BASE_URL=${JELLYFIN_BASE_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - TMDB_KEY=${TMDB_KEY}
      - SUB_SEARCH_DIR=${SUB_SEARCH_DIR}
      - TMDB_BASE_URL=${TMDB_BASE_URL}
      - TORRENT_BASE_URL=${TORRENT_BASE_URL}
    volumes:
      - .:/app
      - /data/downloads:/downloads
